name: ci

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: Install dependencies
        run: npm ci

      - name: Run Test
        run: npm run test:ci -w @conken-oss-pkgs/services

      - name: Create Coverage Report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # pass output from the previous step by id.
          path: packages/services/coverage/report.txt