name: ci-pr

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: Install dependencies
        run: npm ci

      - name: Run Test
        run: npm run test:ci -w @conken-oss-pkgs/services

      - name: Generate Service Coverage Report
        run: |
          echo '# Coverage Of Services :rocket:' >> service-coverage.txt
          echo 'coverage とは: https://overworker.hatenablog.jp/entry/2021/03/09/011110' >> service-coverage.txt
          echo 'コメント生成方法: https://github.com/marocchino/sticky-pull-request-comment' >> service-coverage.txt
          cat packages/services/coverage/report.txt | sed '1d' | sed '$d' >> service-coverage.txt

      - name: Comment Service Coverage Report
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          # pass output from the previous step by id.
          path: service-coverage.txt