name: ci

on:
  push:

jobs:
  ci:
    runs-on: ubuntu-latest
    env:
      # Remote Caching 機能を利用するための環境変数
      # @see https://turbo.build/repo/docs/ci/github-actions
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      
      - name: Install dependencies
        run: npm ci

      # @see https://blog.chick-p.work/blog/github-actions-job-summary
      - name: Run test:ci
        run: |
          npm run test:ci
          echo '# Coverage Of Services :rocket:' >> $GITHUB_STEP_SUMMARY
          cat packages/services/coverage/report.txt | sed '1d' | sed '$d' >> $GITHUB_STEP_SUMMARY

      - name: Check lint
        run: npm run lint

      - name: Run format
        run: npm run format

      - name: Run typecheck
        run: npm run typecheck

