name: Publish "services" to npmjs 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: production
    env:
      # Remote Caching 機能を利用するための環境変数
      # @see https://turbo.build/repo/docs/ci/github-actions
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      # キャッシュを利用して、npm ci の実行時間を短縮
      # @see https://dev.classmethod.jp/articles/cicd-npm-ci-cache/
      - name: Cache npm dir
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Publish "services"
        run: npm publish -w @unwheel-pkg/services
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
