name: Publish "frontend-react-emotion" to npmjs 

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: 
      name: production
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Dependencies
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Publish "frontend-react-emotion"
        run: npm publish -w packages/frontend-react-emotion/
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
